development:
  adapter: postgresql
  encoding: unicode
  database: development
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: test
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: production
  password:
